package tables;
// Generated 20 Apr, 2020 12:31:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCustomer generated by hbm2java
 */
public class TblCustomer  implements java.io.Serializable {


     private Integer cid;
     private String cname;
     private String cemail;
     private String cpass;
     private String caddr;
     private String ccont;
     private Set tblCarts = new HashSet(0);
     private Set tblOrders = new HashSet(0);

    public TblCustomer() {
    }

	
    public TblCustomer(String cname, String cemail, String cpass, String caddr, String ccont) {
        this.cname = cname;
        this.cemail = cemail;
        this.cpass = cpass;
        this.caddr = caddr;
        this.ccont = ccont;
    }
    public TblCustomer(String cname, String cemail, String cpass, String caddr, String ccont, Set tblCarts, Set tblOrders) {
       this.cname = cname;
       this.cemail = cemail;
       this.cpass = cpass;
       this.caddr = caddr;
       this.ccont = ccont;
       this.tblCarts = tblCarts;
       this.tblOrders = tblOrders;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public String getCemail() {
        return this.cemail;
    }
    
    public void setCemail(String cemail) {
        this.cemail = cemail;
    }
    public String getCpass() {
        return this.cpass;
    }
    
    public void setCpass(String cpass) {
        this.cpass = cpass;
    }
    public String getCaddr() {
        return this.caddr;
    }
    
    public void setCaddr(String caddr) {
        this.caddr = caddr;
    }
    public String getCcont() {
        return this.ccont;
    }
    
    public void setCcont(String ccont) {
        this.ccont = ccont;
    }
    public Set getTblCarts() {
        return this.tblCarts;
    }
    
    public void setTblCarts(Set tblCarts) {
        this.tblCarts = tblCarts;
    }
    public Set getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set tblOrders) {
        this.tblOrders = tblOrders;
    }




}


