package tables;
// Generated 20 Apr, 2020 12:31:14 PM by Hibernate Tools 4.3.1



/**
 * TblCart generated by hbm2java
 */
public class TblCart  implements java.io.Serializable {


     private Integer cartid;
     private TblCustomer tblCustomer;
     private TblProduct tblProduct;
     private int pqty;

    public TblCart() {
    }

    public TblCart(TblCustomer tblCustomer, TblProduct tblProduct, int pqty) {
       this.tblCustomer = tblCustomer;
       this.tblProduct = tblProduct;
       this.pqty = pqty;
    }
   
    public Integer getCartid() {
        return this.cartid;
    }
    
    public void setCartid(Integer cartid) {
        this.cartid = cartid;
    }
    public TblCustomer getTblCustomer() {
        return this.tblCustomer;
    }
    
    public void setTblCustomer(TblCustomer tblCustomer) {
        this.tblCustomer = tblCustomer;
    }
    public TblProduct getTblProduct() {
        return this.tblProduct;
    }
    
    public void setTblProduct(TblProduct tblProduct) {
        this.tblProduct = tblProduct;
    }
    public int getPqty() {
        return this.pqty;
    }
    
    public void setPqty(int pqty) {
        this.pqty = pqty;
    }




}


