package tables;
// Generated 20 Apr, 2020 12:31:14 PM by Hibernate Tools 4.3.1



/**
 * TblFaq generated by hbm2java
 */
public class TblFaq  implements java.io.Serializable {


     private Integer fid;
     private TblProduct tblProduct;
     private String question;
     private String answer;

    public TblFaq() {
    }

    public TblFaq(TblProduct tblProduct, String question, String answer) {
       this.tblProduct = tblProduct;
       this.question = question;
       this.answer = answer;
    }
   
    public Integer getFid() {
        return this.fid;
    }
    
    public void setFid(Integer fid) {
        this.fid = fid;
    }
    public TblProduct getTblProduct() {
        return this.tblProduct;
    }
    
    public void setTblProduct(TblProduct tblProduct) {
        this.tblProduct = tblProduct;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


