package tables;
// Generated 20 Apr, 2020 12:31:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblOrder generated by hbm2java
 */
public class TblOrder  implements java.io.Serializable {


     private Integer oid;
     private TblCustomer tblCustomer;
     private int delivered;
     private int amount;
     private Date date;
     private Set tblOrderLists = new HashSet(0);

    public TblOrder() {
    }

	
    public TblOrder(TblCustomer tblCustomer, int delivered, int amount, Date date) {
        this.tblCustomer = tblCustomer;
        this.delivered = delivered;
        this.amount = amount;
        this.date = date;
    }
    public TblOrder(TblCustomer tblCustomer, int delivered, int amount, Date date, Set tblOrderLists) {
       this.tblCustomer = tblCustomer;
       this.delivered = delivered;
       this.amount = amount;
       this.date = date;
       this.tblOrderLists = tblOrderLists;
    }
   
    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }
    public TblCustomer getTblCustomer() {
        return this.tblCustomer;
    }
    
    public void setTblCustomer(TblCustomer tblCustomer) {
        this.tblCustomer = tblCustomer;
    }
    public int getDelivered() {
        return this.delivered;
    }
    
    public void setDelivered(int delivered) {
        this.delivered = delivered;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getTblOrderLists() {
        return this.tblOrderLists;
    }
    
    public void setTblOrderLists(Set tblOrderLists) {
        this.tblOrderLists = tblOrderLists;
    }




}


