package tables;
// Generated 20 Apr, 2020 12:31:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblProduct generated by hbm2java
 */
public class TblProduct  implements java.io.Serializable {


     private Integer pid;
     private String pname;
     private int pqty;
     private String pimg;
     private int pprice;
     private String pdesc;
     private Set tblCarts = new HashSet(0);
     private Set tblFaqs = new HashSet(0);
     private Set tblOrderLists = new HashSet(0);

    public TblProduct() {
    }

	
    public TblProduct(String pname, int pqty, String pimg, int pprice, String pdesc) {
        this.pname = pname;
        this.pqty = pqty;
        this.pimg = pimg;
        this.pprice = pprice;
        this.pdesc = pdesc;
    }
    public TblProduct(String pname, int pqty, String pimg, int pprice, String pdesc, Set tblCarts, Set tblFaqs, Set tblOrderLists) {
       this.pname = pname;
       this.pqty = pqty;
       this.pimg = pimg;
       this.pprice = pprice;
       this.pdesc = pdesc;
       this.tblCarts = tblCarts;
       this.tblFaqs = tblFaqs;
       this.tblOrderLists = tblOrderLists;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public int getPqty() {
        return this.pqty;
    }
    
    public void setPqty(int pqty) {
        this.pqty = pqty;
    }
    public String getPimg() {
        return this.pimg;
    }
    
    public void setPimg(String pimg) {
        this.pimg = pimg;
    }
    public int getPprice() {
        return this.pprice;
    }
    
    public void setPprice(int pprice) {
        this.pprice = pprice;
    }
    public String getPdesc() {
        return this.pdesc;
    }
    
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc;
    }
    public Set getTblCarts() {
        return this.tblCarts;
    }
    
    public void setTblCarts(Set tblCarts) {
        this.tblCarts = tblCarts;
    }
    public Set getTblFaqs() {
        return this.tblFaqs;
    }
    
    public void setTblFaqs(Set tblFaqs) {
        this.tblFaqs = tblFaqs;
    }
    public Set getTblOrderLists() {
        return this.tblOrderLists;
    }
    
    public void setTblOrderLists(Set tblOrderLists) {
        this.tblOrderLists = tblOrderLists;
    }




}


